<s:set name="SERVELET_PATH" value="#request.get('javax.servlet.forward.context_path')"/>
<s:set name="URL_PATH" value="#request.get('javax.servlet.forward.context_path')"/>
<s:set name="JS_PATH" value="#URL_PATH+'/js/'"/>
<s:set name="IMAGE_PATH" value="#URL_PATH+'/img/'"/>
<s:set name="CSS_PATH" value="#URL_PATH+'/css/'"/>
<s:set name="ZYBXJS_PATH" value="#URL_PATH+'/jsp/js/zybx/'"/>
<s:set name="ZYBXQYJS_PATH" value="#URL_PATH+'/jsp/js/zybx/zybxqy/'"/>
